/*
 * Gurjit Singh
 * Friday October 25th - 2019
 * This program displays the math methods
 */

/**
 *
 * @author gusin5788
 */
public class frmmathmethods extends javax.swing.JFrame {

    /**
     * Creates new form frmmathmethods
     */
    public frmmathmethods() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        lblFirst = new javax.swing.JLabel();
        lblSecond = new javax.swing.JLabel();
        lblThird = new javax.swing.JLabel();
        lblFourth = new javax.swing.JLabel();
        lblFifth = new javax.swing.JLabel();
        lblSixth = new javax.swing.JLabel();
        lblSeventh = new javax.swing.JLabel();
        lblEighth = new javax.swing.JLabel();
        lblNinth = new javax.swing.JLabel();
        lblTenth = new javax.swing.JLabel();
        lblEleventh = new javax.swing.JLabel();
        lblTwelfth = new javax.swing.JLabel();
        lblThirteenth = new javax.swing.JLabel();
        lblFourteenth = new javax.swing.JLabel();
        lblFifteenth = new javax.swing.JLabel();
        lblSixteenth = new javax.swing.JLabel();
        lblSeventeenth = new javax.swing.JLabel();
        txtFirst = new javax.swing.JTextField();
        txtSecond = new javax.swing.JTextField();
        txtThird = new javax.swing.JTextField();
        txtFourth = new javax.swing.JTextField();
        txtFifth = new javax.swing.JTextField();
        txtSixth = new javax.swing.JTextField();
        txtSeventh = new javax.swing.JTextField();
        txtEighth = new javax.swing.JTextField();
        txtNinth = new javax.swing.JTextField();
        txtTenth = new javax.swing.JTextField();
        txtEleventh = new javax.swing.JTextField();
        txtTwelfth = new javax.swing.JTextField();
        btnFirst = new javax.swing.JButton();
        btnSecond = new javax.swing.JButton();
        btnThird = new javax.swing.JButton();
        btnFourth = new javax.swing.JButton();
        btnFifth = new javax.swing.JButton();
        btnSixth = new javax.swing.JButton();
        btnSeventh = new javax.swing.JButton();
        btnEighth = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFirst.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblFirst.setForeground(new java.awt.Color(204, 153, 0));
        lblFirst.setText("Math Methods");
        getContentPane().add(lblFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        lblSecond.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        lblSecond.setForeground(new java.awt.Color(255, 153, 0));
        lblSecond.setText("Enter two numbers and click the button. The program will display the largest of the two numbers:");
        getContentPane().add(lblSecond, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        lblThird.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        lblThird.setForeground(new java.awt.Color(255, 153, 0));
        lblThird.setText("Enter two numbers and click the button. The program will display the smallest of the two numbers:");
        getContentPane().add(lblThird, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        lblFourth.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        lblFourth.setForeground(new java.awt.Color(255, 153, 0));
        lblFourth.setText("Enter two numbers and click the button. The program will display the first number to the power of the second:");
        getContentPane().add(lblFourth, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        lblFifth.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        lblFifth.setForeground(new java.awt.Color(255, 153, 0));
        lblFifth.setText("Enter the length of two sides of a right triangle. The program will display the hypotenuse of the triangle:");
        getContentPane().add(lblFifth, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        lblSixth.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        lblSixth.setForeground(new java.awt.Color(255, 153, 0));
        lblSixth.setText("Enter a decimal value. The program will display the value rounded up to the nearest integer:");
        getContentPane().add(lblSixth, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        lblSeventh.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        lblSeventh.setForeground(new java.awt.Color(255, 153, 0));
        lblSeventh.setText("Enter a decimal value. The program will display the value rounded down to the nearest integer:");
        getContentPane().add(lblSeventh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        lblEighth.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        lblEighth.setForeground(new java.awt.Color(255, 153, 0));
        lblEighth.setText("Enter an integer. The program will display the square root of the integer:");
        getContentPane().add(lblEighth, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        lblNinth.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        lblNinth.setForeground(new java.awt.Color(255, 153, 0));
        lblNinth.setText("Enter an angle in degrees. The program will display the angle in radians.");
        getContentPane().add(lblNinth, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));

        lblTenth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        lblTenth.setText("_______");
        getContentPane().add(lblTenth, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, -1));

        lblEleventh.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        lblEleventh.setText("_______");
        getContentPane().add(lblEleventh, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, -1));

        lblTwelfth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        lblTwelfth.setText("_______");
        getContentPane().add(lblTwelfth, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));

        lblThirteenth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        lblThirteenth.setText("_______");
        getContentPane().add(lblThirteenth, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, -1, -1));

        lblFourteenth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        lblFourteenth.setText("_______");
        getContentPane().add(lblFourteenth, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, -1, -1));

        lblFifteenth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        lblFifteenth.setText("_______");
        getContentPane().add(lblFifteenth, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, -1, -1));

        lblSixteenth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        lblSixteenth.setText("_______");
        getContentPane().add(lblSixteenth, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 530, -1, -1));

        lblSeventeenth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        lblSeventeenth.setText("_______");
        getContentPane().add(lblSeventeenth, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 600, -1, -1));

        txtFirst.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        getContentPane().add(txtFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 60, -1));

        txtSecond.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        getContentPane().add(txtSecond, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 60, -1));

        txtThird.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        getContentPane().add(txtThird, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 60, -1));

        txtFourth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        getContentPane().add(txtFourth, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 60, -1));

        txtFifth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        getContentPane().add(txtFifth, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 60, -1));

        txtSixth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        getContentPane().add(txtSixth, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 60, -1));

        txtSeventh.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        getContentPane().add(txtSeventh, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 60, -1));

        txtEighth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        getContentPane().add(txtEighth, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 60, -1));

        txtNinth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        getContentPane().add(txtNinth, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 60, -1));

        txtTenth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        getContentPane().add(txtTenth, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 60, -1));

        txtEleventh.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        getContentPane().add(txtEleventh, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 60, -1));

        txtTwelfth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        getContentPane().add(txtTwelfth, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 590, 60, -1));

        btnFirst.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnFirst.setText("Largest");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        getContentPane().add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        btnSecond.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnSecond.setText("Smallest");
        btnSecond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecondActionPerformed(evt);
            }
        });
        getContentPane().add(btnSecond, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        btnThird.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnThird.setText("Power");
        btnThird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThirdActionPerformed(evt);
            }
        });
        getContentPane().add(btnThird, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        btnFourth.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnFourth.setText("Hypotenuse");
        btnFourth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourthActionPerformed(evt);
            }
        });
        getContentPane().add(btnFourth, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));

        btnFifth.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnFifth.setText("Rounded Up");
        btnFifth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFifthActionPerformed(evt);
            }
        });
        getContentPane().add(btnFifth, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, -1, -1));

        btnSixth.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnSixth.setText("Rounded Down");
        btnSixth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSixthActionPerformed(evt);
            }
        });
        getContentPane().add(btnSixth, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, -1, -1));

        btnSeventh.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnSeventh.setText("Square Root");
        btnSeventh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeventhActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeventh, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, -1, -1));

        btnEighth.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnEighth.setText("In Radians");
        btnEighth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEighthActionPerformed(evt);
            }
        });
        getContentPane().add(btnEighth, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 590, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        double num1 = Double.parseDouble(txtFirst.getText());
        double num2 = Double.parseDouble(txtSecond.getText());
        double largest = (Math.max(num1, num2));
        String largest1 = String.valueOf(largest);
        
        lblTenth.setText(largest1);
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnSecondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecondActionPerformed
        double num1 = Double.parseDouble(txtThird.getText());
        double num2 = Double.parseDouble(txtFourth.getText());
        double smallest = (Math.min(num1, num2));
        String smallest1 = String.valueOf(smallest);
        
        lblEleventh.setText(smallest1);
    }//GEN-LAST:event_btnSecondActionPerformed

    private void btnThirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThirdActionPerformed
        double num1 = Double.parseDouble(txtFifth.getText());
        double num2 = Double.parseDouble(txtSixth.getText());
        double power = (Math.pow(num1, num2));
        String power1 = String.valueOf(power);
        
        lblTwelfth.setText(power1);
    }//GEN-LAST:event_btnThirdActionPerformed

    private void btnFourthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFourthActionPerformed
        double length1 = Double.parseDouble(txtSeventh.getText());
        double length2 = Double.parseDouble(txtEighth.getText());
        double hypotenuse = (Math.hypot(length1, length2));
        String hypotenuse1 = String.valueOf(hypotenuse);
        
        lblThirteenth.setText(hypotenuse1);
    }//GEN-LAST:event_btnFourthActionPerformed

    private void btnFifthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFifthActionPerformed
        double num = Double.parseDouble(txtNinth.getText());
        double roundedup = (Math.ceil(num));
        String roundedup1 = String.valueOf(roundedup);
        
        lblFourteenth.setText(roundedup1);
    }//GEN-LAST:event_btnFifthActionPerformed

    private void btnSixthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSixthActionPerformed
        double num = Double.parseDouble(txtTenth.getText());
        double roundeddown = (Math.floor(num));
        String roundeddown1 = String.valueOf(roundeddown);
        
        lblFifteenth.setText(roundeddown1);
    }//GEN-LAST:event_btnSixthActionPerformed

    private void btnSeventhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeventhActionPerformed
        double num = Double.parseDouble(txtEleventh.getText());
        double squareroot = (Math.sqrt(num));
        String squareroot1 = String.valueOf(squareroot);
        
        lblSixteenth.setText(squareroot1);
    }//GEN-LAST:event_btnSeventhActionPerformed

    private void btnEighthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEighthActionPerformed
        double angle = Double.parseDouble(txtTwelfth.getText());
        double radians = (Math.toRadians(angle));
        String radians1 = String.valueOf(radians);
        
        lblSeventeenth.setText(radians1);
    }//GEN-LAST:event_btnEighthActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmmathmethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmmathmethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmmathmethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmmathmethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmmathmethods().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEighth;
    private javax.swing.JButton btnFifth;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnFourth;
    private javax.swing.JButton btnSecond;
    private javax.swing.JButton btnSeventh;
    private javax.swing.JButton btnSixth;
    private javax.swing.JButton btnThird;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblEighth;
    private javax.swing.JLabel lblEleventh;
    private javax.swing.JLabel lblFifteenth;
    private javax.swing.JLabel lblFifth;
    private javax.swing.JLabel lblFirst;
    private javax.swing.JLabel lblFourteenth;
    private javax.swing.JLabel lblFourth;
    private javax.swing.JLabel lblNinth;
    private javax.swing.JLabel lblSecond;
    private javax.swing.JLabel lblSeventeenth;
    private javax.swing.JLabel lblSeventh;
    private javax.swing.JLabel lblSixteenth;
    private javax.swing.JLabel lblSixth;
    private javax.swing.JLabel lblTenth;
    private javax.swing.JLabel lblThird;
    private javax.swing.JLabel lblThirteenth;
    private javax.swing.JLabel lblTwelfth;
    private javax.swing.JTextField txtEighth;
    private javax.swing.JTextField txtEleventh;
    private javax.swing.JTextField txtFifth;
    private javax.swing.JTextField txtFirst;
    private javax.swing.JTextField txtFourth;
    private javax.swing.JTextField txtNinth;
    private javax.swing.JTextField txtSecond;
    private javax.swing.JTextField txtSeventh;
    private javax.swing.JTextField txtSixth;
    private javax.swing.JTextField txtTenth;
    private javax.swing.JTextField txtThird;
    private javax.swing.JTextField txtTwelfth;
    // End of variables declaration//GEN-END:variables
}
